### ISSUE TITLE
 Error installing Moya

### ISSUE THREAD

**Issue by ghost** [jairoeli/Habit#12]
[!] Error installing Moya
[!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C /var/folders/lb/cp793sm10k54t_cm2r672ghc0000gn/T/d20171010-4551-1pcrx3r checkout --quiet 7c74420a86b0b492ffa989aadb2c542a3d3c6c23

fatal: reference is not a tree: 7c74420a86b0b492ffa989aadb2c542a3d3c6c23

**Comment by jairoeli** [comment]
Just updated the latest master branch. Be sure to check their dependencies' latest version.
